[app]
log_level = "debug"
log_file  = "/tmp/logs/walkrie.log"
log_max_size_mb  = 10
log_max_files    = 5
batch_size       = 20
batch_timout_ms  = 50

[[source]]
host        = "localhost"
port        = "5432"
dbname      = "hr_demo"
user        = "walkrie_demo"
password    = "walkrie"
slot_name   = "cv_cdc_slot"
publication = "cv_pub"

[[sink]]
type            = "pgvector"
host            = "localhost"
port            = "5432"
dbname          = "hr_demo"
user            = "walkrie_demo"
password        = "walkrie"
table           = "public.candidate_search"
embed_column    = "embedding"

 [[sink.table_mapping]]
 source_table = "candidates"

    [[sink.table_mapping.columns]]
    source_column = "id"
    sink_column   = "candidate_id"
    role          = "id"

    [[sink.table_mapping.columns]]
    source_column = "cv_text"
    sink_column   = "cv_text"
    role          = "embed"

    [[sink.table_mapping.columns]]
    source_column = "full_name"
    sink_column   = "full_name"
    role          = "metadata"

    [[sink.table_mapping.columns]]
    source_column = "years_experience"
    sink_column   = "years_experience"
    role          = "metadata"

    [[sink.table_mapping.columns]]
    source_column = "location"
    sink_column   = "location"
    role          = "metadata"

[embedding]
provider   = "llama"
#model_path = "/home/debian/models/bge-m3/bge-m3-Q4_K_M.gguf"
model_path = "/home/debian/models/bge-m3/bge-m3-Q8_0.gguf"
dimensions = 1024
n_threads  = 4
n_ctx      = 512
